### ISSUE TITLE
Make status bar colour match app bar colour

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1778]
Noticed this commit in zCard: https://github.com/ziadOUA/zCard/commit/2164e4c4cff41b61db03b6cb791efea6e7ec7d45

While I don't think we can use the commit as-is as it changes quite some unrelated code too, I think the general idea of keeping the status bar colour up-to-date with the app bar colour is quite good.

The current situation is a bit weird, on the MainActivity the status bar colour never seems to completely match the app bar colour, except when pure black OLED is turned on, on other activities the status bar colour seems to match until you start scrolling.

Perhaps this code could be added in a more generic way in the `CatimaAppCompatActivity.java` class?

Something like:
```
if (binding.appbar != null) {
    getWindow().setStatusBarColor(binding.appbar.getBackgroundColor());

    binding.appbar.addLiftOnScrollListener((elevation, backgroundColor) -> {
        getWindow().setStatusBarColor(backgroundColor);
    });
};
```
at the end of the `onCreate` after `Utils.patchColors`? (Untested pseudocode)

Would be nice to investigate although I think this isn't really high priority as I never even noticed the colours being slightly off myself until seeing the zCard patch.

**Comment by fynngodau** [comment]
I like solving issues like this by having the app bar itself also draw under the status bar. This guarantees that both have exactly the same color. I implemented this in the layouts of main, group, and settings activity (as those are the ones where it seemed relevant, as the other activities don't seem to have the same kind of tint-on-scroll effect – is this intended?) in  #1817.

**Comment by TheLastProject** [comment]
> as the other activities don't seem to have the same kind of tint-on-scroll effect – is this intended

That's definitely not intended. To be honest, I don't know where the color change comes from in the first place, it seems to be something the Android Material Design colour libraries did by default. At least, I don't remember doing anything special to get this behaviour. So it's confusing to me why it wouldn't always behave the same.

**Comment by fynngodau** [comment]
> To be honest, I don't know where the color change comes from in the first place, it seems to be something the Android Material Design colour libraries did by default. At least, I don't remember doing anything special to get this behaviour. So it's confusing to me why it wouldn't always behave the same.

While I can't say _why_ this is the case, it seems that this behavior is enabled automatically to work with some views, but doesn't support some others. For instance, the following diff enables the tint-on-scroll / color change effect in the about activity:

```
diff --git a/app/src/main/res/layout/about_activity.xml b/app/src/main/res/layout/about_activity.xml
index 12cdf0bb..7bbe708f 100644
--- a/app/src/main/res/layout/about_activity.xml
+++ b/app/src/main/res/layout/about_activity.xml
@@ -20,7 +20,7 @@
 
     </com.google.android.material.appbar.AppBarLayout>
 
-    <ScrollView
+    <androidx.core.widget.NestedScrollView
         android:layout_width="match_parent"
         android:layout_height="match_parent"
         android:layout_marginTop="?attr/actionBarSize"
@@ -379,5 +379,5 @@
                     app:layout_constraintTop_toTopOf="parent" />
             </androidx.constraintlayout.widget.ConstraintLayout>
         </LinearLayout>
-    </ScrollView>
+    </androidx.core.widget.NestedScrollView>
 </androidx.coordinatorlayout.widget.CoordinatorLayout>
```

Seems that `RecyclerView` and whatever the settings fragment uses in the background are supported, while `ScrollView` isn't.

**Comment by TheLastProject** [comment]
Ah, interesting! That means that getting everything to be consistent shouldn't be *too* hard. Hopefully.

Then we still have the curious situation where the header colour is inconsistent between activities, but I assume there is some logic behind that too (and this seems to be common in many apps and I never noticed until I started looking this closely because of this conversation), so as long as we can make sure that the header colour is the same as the status bar colour everywhere that should probably be enough to make the app feel better integrated and more modern. And it looks like the `fitsSystemWindows` together with a few minor view type changes like that should suffice in making that the case everywhere.

Given this change will need testing on every single Android version, we might as well consider swapping some view types for similar types to create more consistency between the activities as well now so we can make sure it's all nice and consistent. What do you think?

**Comment by fynngodau** [comment]
> What do you think?

I care about visual details to be right, so I've added corresponding changes to #1817. However I will not have time to test on every supported Android version myself.

From https://stackoverflow.com/a/35181870/ and https://stackoverflow.com/a/30118423/, I gathered that it is sufficient to set `app:layout_behavior="@string/appbar_scrolling_view_behavior"` on `ScrollView` _if_ `android:nestedScrollingEnabled="true"` is set; but from my testing, it leads to bugs that can be avoided when using `androidx.core.widget.NestedScrollView` instead.

One problem is the `ListView` in `barcode_selector_activity.xml`. While the same as with `ScrollView` applies, this leads to odd visual behavior; however, it can't simply be replaced with another component unless we were to entirely switch it out for a `RecyclerView`.
